export const schemasAnexo2P = [
    {
      "nombresApellidos": {
        "type": "text",
        "content": "",
        "position": {
          "x": 52.58,
          "y": 48.76
        },
        "width": 141.57,
        "height": 6.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "departamento": {
        "type": "text",
        "content": "",
        "position": {
          "x": 52.58,
          "y": 57.5
        },
        "width": 141.31,
        "height": 8.67,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "tituloPublicacion": {
        "type": "text",
        "content": "",
        "position": {
          "x": 73.84,
          "y": 80.65
        },
        "width": 126.23,
        "height": 13.17,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "nombreRevista": {
        "type": "text",
        "content": "",
        "position": {
          "x": 73.84,
          "y": 95.53
        },
        "width": 126.23,
        "height": 11.58,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "autoresEPN": {
        "type": "text",
        "content": "",
        "position": {
          "x": 73.84,
          "y": 109
        },
        "width": 126.23,
        "height": 17.67,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "autoresExternos": {
        "type": "text",
        "content": "",
        "position": {
          "x": 73.84,
          "y": 128.84
        },
        "width": 125.7,
        "height": 16.61,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "baseDatos": {
        "type": "text",
        "content": "",
        "position": {
          "x": 74.1,
          "y": 147.51
        },
        "width": 125.7,
        "height": 12.38,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "cuartilPublicacion": {
        "type": "text",
        "content": "",
        "position": {
          "x": 73.84,
          "y": 162.15
        },
        "width": 125.7,
        "height": 11.85,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "valorPublicacion": {
        "type": "text",
        "content": "",
        "position": {
          "x": 62.27,
          "y": 189.32
        },
        "width": 40.5,
        "height": 15.02,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "limiteFecha": {
        "type": "text",
        "content": "",
        "position": {
          "x": 152.98,
          "y": 189.32
        },
        "width": 45,
        "height": 15.02,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "metodoPagoTransferencia": {
        "type": "text",
        "content": "",
        "position": {
          "x": 72.19,
          "y": 212.71
        },
        "width": 2.93,
        "height": 3.11,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "metodoPagoOtra": {
        "type": "text",
        "content": "",
        "position": {
          "x": 184.37,
          "y": 212.85
        },
        "width": 2.14,
        "height": 3.11,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      }
    },
    {
      "nombresAp": {
        "type": "text",
        "content": "",
        "position": {
          "x": 53.81,
          "y": 42.46
        },
        "width": 100.56,
        "height": 3.64,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "departament": {
        "type": "text",
        "content": "",
        "position": {
          "x": 41.41,
          "y": 46.29
        },
        "width": 125.7,
        "height": 3.64,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      }
    }
  ];