export const schemasAnexo1P = [
    {
      "nombresApellidos": {
        "type": "text",
        "content": "",
        "position": {
          "x": 58.49,
          "y": 64.35
        },
        "width": 138.66,
        "height": 9.47,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "depertamento": {
        "type": "text",
        "content": "",
        "position": {
          "x": 58.49,
          "y": 75.48
        },
        "width": 138.39,
        "height": 8.67,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "codigoProyecto": {
        "type": "text",
        "content": "",
        "position": {
          "x": 59.93,
          "y": 86.61
        },
        "width": 136.81,
        "height": 6.03,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "tituloPublicacion": {
        "type": "text",
        "content": "",
        "position": {
          "x": 71.24,
          "y": 115.14
        },
        "width": 125.7,
        "height": 11.85,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "nombreRevista": {
        "type": "text",
        "content": "",
        "position": {
          "x": 71.48,
          "y": 129.08
        },
        "width": 125.43,
        "height": 11.32,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "autoresEPN": {
        "type": "text",
        "content": "",
        "position": {
          "x": 71.24,
          "y": 143.25
        },
        "width": 125.7,
        "height": 17.14,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "autoresExternos": {
        "type": "text",
        "content": "",
        "position": {
          "x": 71.24,
          "y": 162.62
        },
        "width": 125.69,
        "height": 15.02,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "baseDatos": {
        "type": "text",
        "content": "",
        "position": {
          "x": 71.01,
          "y": 179.87
        },
        "width": 125.7,
        "height": 11.32,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "cuartilPublicacion": {
        "type": "text",
        "content": "",
        "position": {
          "x": 71.24,
          "y": 193.81
        },
        "width": 125.43,
        "height": 11.05,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "valorPublicacion": {
        "type": "text",
        "content": "",
        "position": {
          "x": 62.03,
          "y": 224.54
        },
        "width": 37.85,
        "height": 16.07,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "limiteFecha": {
        "type": "text",
        "content": "",
        "position": {
          "x": 150.15,
          "y": 224.75
        },
        "width": 44.74,
        "height": 16.08,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      }
    },
    {
      "metodoPagoTransferencia": {
        "type": "text",
        "content": "",
        "position": {
          "x": 70.54,
          "y": 15.05
        },
        "width": 2.93,
        "height": 3.65,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "metodoPagoOtra": {
        "type": "text",
        "content": "",
        "position": {
          "x": 181.08,
          "y": 15.65
        },
        "width": 2.66,
        "height": 2.85,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#2573ca",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "nombreDirector": {
        "type": "text",
        "content": "",
        "position": {
          "x": 55.9,
          "y": 94.01
        },
        "width": 107.18,
        "height": 3.38,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto"
      },
      "codigoProyecto2": {
        "type": "text",
        "content": "",
        "position": {
          "x": 78.14,
          "y": 97.87
        },
        "width": 62.72,
        "height": 3.91,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 8,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      }
    }
  ];